version: '3'
services: 
    frontend:
        container_name: react-frontend-container
        restart: always
        build: .
        ports:
            - '3000:3000'
        volumes: ['./:/usr/src/app']
        
        
    mongo:
        container_name: mongo
        image: mongo
        ports: 
            - '27017:27017'